version: "3"

services:
  resume:
    image: nginx:latest
    container_name: resume
    restart: always
    # ports:
    #   - 8000:80
    volumes:
      - /home/ubuntu/projects/resume/web:/usr/share/nginx/html
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    
  cloudflared_resume:
    restart: always
    container_name: cloudflared_resume
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_RESUME}


